In [46]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, roc_curve, auc
import matplotlib.pyplot as plt

In [47]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive', force_remount = True)
path = "drive/My Drive/Colab Notebooks/heart.data.csv"
df = pd.read_csv(path)
df

Mounted at /content/drive


Unnamed: 0     biking    smoking  heart.disease
0             1  30.801246  10.896608      11.769423
1             2  65.129215   2.219563       2.854081
2             3   1.959665  17.588331      17.177803
3             4  44.800196   2.802559       6.816647
4             5  69.428454  15.974505       4.062224
..          ...        ...        ...            ...
493         494  47.660440  27.562464      11.294392
494         495  45.097203  21.385620       9.616762
495         496   8.279743   6.423720      13.495168
496         497  42.345863  20.741328      10.115865
497         498  30.774254  23.610175      11.843556

[498 rows x 4 columns]

In [49]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, roc_curve, auc
import matplotlib.pyplot as plt

In [54]:
df.dropna(inplace = True)

In [55]:
x=df.iloc[df['smoking']].values
y = df.iloc[df['heart.disease']].values
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.25, random_state=1)
print(y_pred)
print(y_test)


[[15.94036307]
 [13.37400977]
 [10.74091775]
 [15.40912321]
 [13.05482615]
 [27.6310864 ]
 [20.71747528]
 [14.26587698]
 [ 9.01507448]
 [ 8.4146892 ]
 [17.43410771]
 [17.19718953]
 [17.09457783]
 [42.88276909]
 [17.00271199]
 [10.4251452 ]
 [14.20904092]
 [37.83362251]
 [21.75464409]
 [12.25164969]
 [10.16928924]
 [47.35142549]
 [16.50275686]
 [ 9.62809151]
 [ 9.59218186]
 [33.13827595]
 [ 8.90112975]
 [11.21768958]
 [17.09457783]
 [42.88276909]
 [17.00271199]
 [10.4251452 ]
 [12.47771877]
 [45.2174755 ]
 [14.20401852]
 [ 9.05400714]
 [10.74639663]
 [38.68048626]
 [24.21214447]
 [12.79515438]
 [17.09457783]
 [42.88276909]
 [17.00271199]
 [10.4251452 ]
 [17.67168521]
 [26.87331277]
 [10.60708013]
 [12.571387  ]
 [13.63193354]
 [37.19266992]
 [15.61436571]
 [10.99469601]
 [17.09457783]
 [42.88276909]
 [17.00271199]
 [10.4251452 ]
 [13.05482615]
 [27.6310864 ]
 [20.71747528]
 [14.26587698]
 [13.05482615]
 [27.6310864 ]
 [20.71747528]
 [14.26587698]
 [11.32350401]
 [35.59442554]
 [12.51283

In [56]:
from sklearn.linear_model import LinearRegression
import numpy as np

model=LinearRegression()
model. fit(x_train,y_train)

print (model. coef_)
print(model.intercept_)


[[ 0.17254748  0.09289112 -0.08733017  0.38190031]
 [ 0.03377367 -0.19973078 -0.13839473 -0.57088896]
 [ 0.010551    0.07617792 -0.12002422  0.49105028]
 [-0.0077471   0.05894214  0.0050991   0.22391589]]
[ 1.66321502 57.24947205  8.04366305  4.5407042 ]


In [57]:
y_pred=model.predict(y_test)
print(y_pred)

[[10.08551939 46.78143008 15.20056527  8.22968364]
 [ 9.25136473 40.41681131 13.98209056  9.3691209 ]
 [ 7.38710953 44.71863719 14.54873881  8.56903755]
 [10.93463748 40.06495626 13.57373332  9.34958841]
 [ 9.74879681 38.69717127 13.42034736  9.62330002]
 [ 9.13154767 39.02147572 13.46276178  9.58528251]
 [ 8.87347706 44.1571811  14.50959415  8.69098143]
 [10.93463748 40.06495626 13.57373332  9.34958841]
 [ 9.44621162 41.0142614  13.21288861  9.09329203]
 [ 8.83760811 37.07446306 13.42018539  9.98886769]
 [10.93463748 40.06495626 13.57373332  9.34958841]
 [10.91839107 45.05003919 14.62737661  8.48296133]
 [ 9.57046487 41.60111968 13.53269932  9.02363692]
 [10.93463748 40.06495626 13.57373332  9.34958841]
 [ 9.25136473 40.41681131 13.98209056  9.3691209 ]
 [ 9.25136473 40.41681131 13.98209056  9.3691209 ]
 [ 9.54844574 42.08114234 14.51101175  9.13140022]
 [ 9.74879681 38.69717127 13.42034736  9.62330002]
 [ 8.42205504 45.73648234 14.7374714   8.37629834]
 [ 9.57046487 41.60111968 13.53

In [59]:
#Performance analysis

from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
import math

print('Mean absolute error:', mean_absolute_error(y_test, y_pred))

print("Mean squared error:", mean_squared_error(y_test, y_pred))
print('variance score:',r2_score(y_test, y_pred))

print('Root Mean Squared Error:',math.sqrt(mean_squared_error(y_test, y_pred)))

Mean absolute error: 7.470030068870194
Mean squared error: 133.3953194494749
variance score: -0.07920582136620696
Root Mean Squared Error: 11.54968914947389
